/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TileStatus =
  "empty" | "planned" | "intentionally_empty" | "generating" | "reviewing" | "accepted" | "failed";
export type RunStatus = "pending" | "running" | "completed" | "failed" | "cancelled";
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "RunStatus".
 */
export type RunStatus1 = "pending" | "running" | "completed" | "failed" | "cancelled";
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "TileStatus".
 */
export type TileStatus1 =
  "empty" | "planned" | "intentionally_empty" | "generating" | "reviewing" | "accepted" | "failed";

/**
 * Umbrella model: exported as JSON Schema and turned into frontend TypeScript types.
 */
export interface ApiSchemas {
  world: World;
  world_detail: WorldDetail;
  tile: Tile;
  tile_detail: TileDetail;
  run: Run;
  event: Event;
  start_run: StartRun;
  enter_result: EnterResult;
  scene: Scene;
  skirt_tile: SkirtTile;
  sprite_entry: SpriteEntry;
  create_world: CreateWorld;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "World".
 */
export interface World {
  id: string;
  name: string;
  radius: number;
  created_at: number;
  parent: ParentLink | null;
  depth: number;
  scale_note: string;
  /**
   * Radius of the region grid inside each tile (set at creation).
   */
  region_radius: number;
  spec: WorldSpec | null;
  style: StyleGuide | null;
  tile_attributes: AttributeDef[];
  anchor_asset_ids: string[];
  materials: {
    [k: string]: MaterialSpec;
  };
  sprites: {
    [k: string]: SpriteEntry;
  };
}
/**
 * A drilled layer: this world is the inside of one tile of its parent world.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "ParentLink".
 */
export interface ParentLink {
  world_id: string;
  q: number;
  r: number;
  context: {
    [k: string]: unknown;
  };
  guide: {
    [k: string]: string;
  };
  routes: Route[];
  notes: {
    [k: string]: string;
  };
  props: {
    [k: string]: string[];
  };
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Route".
 */
export interface Route {
  /**
   * From connector_vocabulary (river, road, corridor...).
   */
  connector: string;
  /**
   * >= 2 waypoints; the route runs tile to tile between them.
   */
  points: Coord[];
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Coord".
 */
export interface Coord {
  q: number;
  r: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "WorldSpec".
 */
export interface WorldSpec {
  title: string;
  /**
   * e.g. 'adventure', 'board game with cards', 'turn-based tactics'.
   */
  genre: string;
  theme: string;
  /**
   * 2-4 sentences.
   */
  lore: string;
  /**
   * Allowed edge/biome terrain names (snake_case), e.g. grass, water, sand, rock, snow.
   */
  terrain_vocabulary: string[];
  /**
   * Allowed linear features that cross tile edges (snake_case), e.g. road, river, wall.
   */
  connector_vocabulary: string[];
  /**
   * General layout direction, e.g. 'mountains north, coast east'.
   */
  directional_notes: string;
  /**
   * Size of every sprite relative to the tile, world-wide (0.3-1.5): 1 when a tile is a landscape chunk or a room, ~0.5 when a tile is a city block (people and cars next to real buildings), up to 1.3 for close-up interiors or board-game spaces.
   */
  prop_scale: number;
}
/**
 * Shared visual contract for every tile in a world. Set once, then reused.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "StyleGuide".
 */
export interface StyleGuide {
  /**
   * Master palette, 12-32 '#rrggbb' colors. Every tile pixel maps to one.
   */
  palette: string[];
  /**
   * Tile ground resolution in pixels (set by the engine from the run options).
   */
  tile_px: number;
  /**
   * Camera description, e.g. 'top-down orthographic'.
   */
  view: string;
  /**
   * e.g. 'from the top-left'.
   */
  light_direction: string;
  /**
   * Outline rule, e.g. 'no outlines' or '1px dark outline on props'.
   */
  outline: string;
  /**
   * Short art-direction keywords appended to every image prompt.
   */
  style_keywords: string;
}
/**
 * One attribute tile agents may set. The super defines these; we compile them to JSON Schema.
 *
 * This *is* the restricted meta-schema: the super can't emit arbitrary JSON Schema, only
 * typed, bounded attributes, so the compiled schema is always valid for strict structured
 * output and for jsonschema validation.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "AttributeDef".
 */
export interface AttributeDef {
  /**
   * snake_case identifier
   */
  name: string;
  type: "enum" | "enum_list" | "integer" | "number" | "boolean" | "string";
  description: string;
  /**
   * Allowed values for enum / enum_list types; empty otherwise.
   */
  enum_values: string[];
  /**
   * Lower bound for integer/number; null otherwise.
   */
  minimum: number | null;
  /**
   * Upper bound for integer/number; null otherwise.
   */
  maximum: number | null;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "MaterialSpec".
 */
export interface MaterialSpec {
  /**
   * '#rrggbb'. A 5-step ramp (outline/dark/base/light/hi) is derived.
   */
  base_color: string;
  /**
   * '#rrggbb' for accent decals (flowers, embers, sparkles).
   */
  accent_color: string;
  base_tone: "dark" | "base" | "light";
  liquid: boolean;
  /**
   * 0-9 height rank; higher materials get a dark lip where they meet lower ones.
   */
  rank: number;
  /**
   * How this material's own border pixels look: foam (water), glow (lava), lip, none.
   */
  boundary: "lip" | "foam" | "glow" | "none";
  /**
   * How each 8px block is drawn: 'bevel' (lit top-left, shaded bottom-right; stone, dirt, grass, obsidian), 'outline' (dark 1px frame: bricks, planks, tiles), 'flat' (liquids, snow, sand).
   */
  block_style: "bevel" | "outline" | "flat";
  /**
   * 'straight' for built things: streets, canals, corridors and walls run in straight lines between tile edges; 'organic' (rivers, trails, coasts) meanders.
   */
  edges: "organic" | "straight";
  /**
   * Connectors only: 'dashed' paints a road's dashed centre line and kerbs (streets, highways), 'rails' two rails with sleepers (railways, tram and cable-car lines), 'none' otherwise.
   */
  markings: "none" | "dashed" | "rails";
  /**
   * Connectors only: width relative to the usual (the engine sets it for close-up layers; leave 1).
   */
  width: number;
  /**
   * Base relief level 0-4 (liquids 0, plains 1, hills 2, rock 3+).
   */
  height: number;
  /**
   * Large-scale rise in relief levels (0-40), grown by the engine as a smooth, ridged landform that blends into neighbouring terrains: 0 flat land and water, 2-5 rolling hills, 6-14 foothills and rocky slopes, 15-40 mountains and snow peaks (a level is ~1/18 of a tile's width). Cities on hills can use it too.
   */
  elevation: number;
  /**
   * Relief patterns (<= 3), e.g. ridges.
   */
  height_ops: HeightOp[];
  /**
   * Pattern layers in paint order (<= 8).
   */
  ops: PatternOp[];
  /**
   * Ambient sprites for tiles of this material (<= 2 kinds).
   */
  scatter: ScatterSpec[];
  /**
   * For BUILT terrain only: buildings raised out of this ground as 3D blocks. The material's own colours and ops then describe the streets/yards between them.
   */
  buildings: BuildingsSpec | null;
}
/**
 * Relief pattern, evaluated per BLOCK in world space: selected blocks are raised/lowered by
 * `delta` levels (one level = one pixel-cube high). 'lots' raises building lots (city blocks, with
 * varied heights); 'rooms' raises the walls of a room grid (interiors), leaving doorways.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "HeightOp".
 */
export interface HeightOp {
  op: "patches" | "cellfill" | "stripes" | "speckle" | "lots" | "rooms";
  /**
   * Feature size in pixels (8-48 for block-scale relief).
   */
  scale: number;
  /**
   * 0-1 coverage/density.
   */
  amount: number;
  /**
   * -2..+4 levels added to selected blocks.
   */
  delta: number;
}
/**
 * One layer of a material, evaluated in world pixel coordinates (seamless across tiles).
 *
 * patches:  smooth noise blobs, coverage = amount       stripes: waves at `angle`, period = scale
 * speckle:  random single pixels, density = amount      cells:   voronoi cracks/mortar, width ~ amount
 * cellfill: fill a fraction (amount) of voronoi cells    bevel:   per-cell light/dark bevel (stones)
 * decals:   stamp `pixels` on a jittered grid (cell = scale, density = amount)
 * built environments (cities, interiors):
 * lots:     rectangular building lots on a staggered grid with 2px alleys, lot size = scale,
 *           share of lots filled = amount (each lot varies its shade: rooftops, market stalls)
 * rooms:    wall lines of a room grid (room size = scale) with doorways (door chance = amount)
 * checker:  checkerboard floor tiles (tile size = scale)
 * planks:   wooden floorboards (board length = scale), dark seams
 * bricks:   brick/stone courses (brick length = scale), mortar lines
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "PatternOp".
 */
export interface PatternOp {
  op:
    | "patches"
    | "speckle"
    | "stripes"
    | "cells"
    | "cellfill"
    | "bevel"
    | "decals"
    | "lots"
    | "rooms"
    | "checker"
    | "planks"
    | "bricks";
  tone: "outline" | "dark" | "base" | "light" | "hi" | "accent";
  /**
   * Feature size in pixels (2-16; lots/rooms 10-40).
   */
  scale: number;
  /**
   * 0-1 coverage/density/width, per op.
   */
  amount: number;
  /**
   * Degrees, for stripes.
   */
  angle: number;
  /**
   * Decal pattern (for 'decals'); [] otherwise.
   */
  pixels: DecalPixel[];
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "DecalPixel".
 */
export interface DecalPixel {
  dx: number;
  dy: number;
  tone: "outline" | "dark" | "base" | "light" | "hi" | "accent";
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "ScatterSpec".
 */
export interface ScatterSpec {
  /**
   * Sprite kind placed around this material, e.g. 'oak tree', 'boulder'.
   */
  kind: string;
  /**
   * Sprites per tile of this material (0-8).
   */
  count: number;
  /**
   * Share of this material's tiles that get it (0-1).
   */
  chance: number;
}
/**
 * Buildings as terrain: the engine lays out footprints on the world pixel grid, raises each
 * building FLOOR_LEVELS relief levels per floor (in 3D they are real blocks with pixel-art facades),
 * paints roofs into the ground and leaves the gaps (streets, alleys, yards) in the material's own
 * pattern. Use it for any built terrain: city blocks, row houses, villages, towers, castles, ports.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "BuildingsSpec".
 */
export interface BuildingsSpec {
  /**
   * blocks: staggered city blocks with alleys. rows: terraced/row houses side by side (Victorian streets, old towns). detached: houses with yards (suburbs, villages). towers: few large towers with plazas between (downtowns). compound: one big walled building per lot with a courtyard (castles, cloisters, warehouses).
   */
  layout: "blocks" | "rows" | "detached" | "towers" | "compound";
  /**
   * Typical footprint size in pixels (6-40; a tile is ~55px).
   */
  lot_px: number;
  /**
   * Alley/yard width between buildings in pixels (1-8).
   */
  gap_px: number;
  /**
   * City streets on the world's shared street lattice, so they join up across tiles and districts: 0 = no street grid (villages, castles, estates), 1 = a street on every lattice line (dense blocks about half a tile wide), 2 = every other line (big blocks, a tile wide).
   */
  street_grid: number;
  /**
   * The world's street connector name (e.g. 'street') that the grid streets are paved with, so they look exactly like the connector streets; '' = plain asphalt.
   */
  street_material: string;
  /**
   * Share of lots that hold a building (0.2-1).
   */
  coverage: number;
  /**
   * Floors of the lowest buildings (1-40).
   */
  floors_min: number;
  /**
   * Floors of the tallest buildings (1-60).
   */
  floors_max: number;
  /**
   * Share of buildings near floors_max (the skyline); the rest skew low.
   */
  tall_share: number;
  /**
   * 1-6 '#rrggbb' facade colours, varied per building.
   */
  wall_colors: string[];
  /**
   * 1-4 '#rrggbb' roof colours.
   */
  roof_colors: string[];
  /**
   * Window pattern drawn on the walls: punched (brick/plaster, a grid of windows), glass (curtain-wall towers), bands (office ribbon windows), victorian (tall narrow bays), industrial (sparse high windows), stone (castles, few slits).
   */
  facade: "punched" | "glass" | "bands" | "victorian" | "industrial" | "stone";
  /**
   * Share of lit (warm) windows, 0-1 (night cities high).
   */
  lit: number;
  /**
   * flat, parapet (raised rim), gabled (a ridge), terrace (stepped).
   */
  roof: "flat" | "parapet" | "gabled" | "terrace";
  /**
   * Rooftop details (vents, water tanks), 0-1.
   */
  clutter: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "SpriteEntry".
 */
export interface SpriteEntry {
  kind: string;
  program: SpriteProgram | null;
  prompt: string | null;
  asset_id: string;
  px_w: number;
  px_h: number;
  frames: number;
  fps: number;
  motion: "none" | "sway" | "bob" | "flicker" | "pulse";
  run_id: string | null;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "SpriteProgram".
 */
export interface SpriteProgram {
  /**
   * Canvas width in pixels (4-18). Match the ground's pixel scale.
   */
  width: number;
  /**
   * Canvas height in pixels (4-22).
   */
  height: number;
  /**
   * 1-6 base colors '#rrggbb'; each gets a ramp (dark/base/light/hi).
   */
  colors: string[];
  /**
   * Painted in order (later shapes on top). <= 80.
   */
  shapes: ShapeOp[];
  /**
   * Animation frames (1-4).
   */
  frames: number;
  /**
   * Frame rate if frames > 1.
   */
  fps: number;
  /**
   * Procedural motion applied by the renderer.
   */
  motion: "none" | "sway" | "bob" | "flicker" | "pulse";
}
/**
 * One primitive on the sprite canvas (pixel units, origin top-left).
 *
 * rect: top-left (x, y), size (w, h) | ellipse: center (x, y), radii (w, h)
 * tri: apex (x, y), base at y+h, half-width w | line: (x, y) -> (x+w, y+h) | pixel: (x, y)
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "ShapeOp".
 */
export interface ShapeOp {
  op: "rect" | "ellipse" | "tri" | "line" | "pixel";
  x: number;
  y: number;
  w: number;
  h: number;
  /**
   * Index into the program's colors.
   */
  color: number;
  /**
   * Ramp step of that color.
   */
  tone: "outline" | "dark" | "base" | "light" | "hi";
  /**
   * Auto-shade: lighter upper-left, darker lower-right.
   */
  shade: boolean;
  /**
   * Frames this shape appears in; [] = every frame.
   */
  frames: number[];
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "WorldDetail".
 */
export interface WorldDetail {
  world: World;
  tiles: Tile[];
  runs: Run[];
  active_run_id: string | null;
  last_event_id: number;
  drills: {
    [k: string]: string;
  };
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Tile".
 */
export interface Tile {
  q: number;
  r: number;
  status: TileStatus;
  run_id: string | null;
  biome: string | null;
  summary: string | null;
  attributes: {
    [k: string]: unknown;
  };
  edges: EdgeSpec[] | null;
  asset_id: string | null;
  ground_asset_id: string | null;
  layers: TileLayer[];
  relief: number;
  preview_asset_id: string | null;
  side_color: string | null;
  art_prompt: string | null;
  copy_of: Coord | null;
  copy_mode: ("shallow" | "deep") | null;
  attempts: number;
  directive: Directive | null;
  visibility: "visible" | "fogged" | "hidden";
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "EdgeSpec".
 */
export interface EdgeSpec {
  /**
   * Terrain along this edge; one of the world's terrain_vocabulary.
   */
  terrain: string;
  /**
   * Connectors crossing this edge (subset of connector_vocabulary).
   */
  connectors: string[];
}
/**
 * One visual layer of a tile. The ground layer is the seamless top-face texture. Sprite layers
 * stand on it as upright billboards: side-view pixel art, optionally a horizontal strip of animation
 * frames, plus a procedural motion the renderer applies.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "TileLayer".
 */
export interface TileLayer {
  kind: "ground" | "height" | "facade" | "sprite";
  asset_id: string;
  label: string;
  x: number;
  y: number;
  width: number;
  px_w: number;
  px_h: number;
  frames: number;
  fps: number;
  motion: "none" | "sway" | "bob" | "flicker" | "pulse";
  role: ("landmark" | "prop" | "scatter") | null;
}
/**
 * What the super asks of one tile agent (derived from a PlannedTile, plus retry feedback).
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Directive".
 */
export interface Directive {
  coord: Coord;
  biome: string;
  intent: string;
  features: string[];
  edge_hints: EdgeHint[];
  feedback: string[];
  simplified: boolean;
  duplicate: CopySpec | null;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "EdgeHint".
 */
export interface EdgeHint {
  /**
   * Edge index 0..5 (0 E, 1 NE, 2 NW, 3 W, 4 SW, 5 SE).
   */
  edge: number;
  terrain: string;
  connectors: string[];
}
/**
 * Lets the super reuse a tile instead of generating a new one (cheap filler: open sea, plain
 * desert...). The source must be a non-copy tile in this plan or an accepted tile in the world.
 *
 * - shallow: a linked instance. The copy shares the prototype's art and data, and stays in sync if
 *   the prototype changes later.
 * - deep: an independent snapshot. The copy gets its own record at copy time and never changes
 *   when the prototype does. `copy_of` is kept only as provenance.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "CopySpec".
 */
export interface CopySpec {
  /**
   * 'none' = generate this tile normally.
   */
  mode: "none" | "shallow" | "deep";
  /**
   * Prototype tile q (ignored when mode is 'none').
   */
  source_q: number;
  /**
   * Prototype tile r (ignored when mode is 'none').
   */
  source_r: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Run".
 */
export interface Run {
  id: string;
  world_id: string;
  origin: Coord;
  prompt: string;
  options: RunOptions;
  status: RunStatus;
  created_at: number;
  finished_at: number | null;
  error: string | null;
  stats: RunStats;
  plan: WorldPlan | null;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "RunOptions".
 */
export interface RunOptions {
  /**
   * Upper bound on tiles the super may plan (it picks the shape).
   */
  max_tiles: number;
  /**
   * Deprecated: a hexagon of this radius' worth of tiles.
   */
  radius: number | null;
  /**
   * Ground texture resolution per tile (32-128px). Only for a new world: all tiles of a world share one pixel grid, so extensions keep the world's resolution.
   */
  tile_px: number | null;
  /**
   * Only for a new world: radius of the region grid you find when entering a tile (then locked).
   */
  region_radius: number | null;
  /**
   * Plan every tile within the world radius (drilled layers fill their hex).
   */
  fill_radius: boolean;
  max_attempts: number;
  review_batch: number;
  max_llm_calls: number;
  max_cost_usd: number;
  max_seconds: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "RunStats".
 */
export interface RunStats {
  llm_calls: number;
  input_tokens: number;
  cached_input_tokens: number;
  output_tokens: number;
  cost_usd: number;
  image_cost_usd: number;
  images: number;
  tiles_planned: number;
  tiles_accepted: number;
  tiles_failed: number;
  tiles_copied: number;
  copy_fallbacks: number;
  attempts: number;
  rejections_validation: number;
  rejections_review: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "WorldPlan".
 */
export interface WorldPlan {
  world: WorldSpec;
  style: StyleGuide;
  tile_attributes: AttributeDef[];
  tiles: PlannedTile[];
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "PlannedTile".
 */
export interface PlannedTile {
  q: number;
  r: number;
  /**
   * True to deliberately leave this slot empty.
   */
  leave_empty: boolean;
  /**
   * Dominant terrain, from terrain_vocabulary.
   */
  biome: string;
  /**
   * One sentence: what this tile is and its role in the world.
   */
  intent: string;
  /**
   * Notable features/props, e.g. 'ruined tower', 'pine trees'.
   */
  features: string[];
  /**
   * Edge constraints the super wants (may be partial).
   */
  edge_hints: EdgeHint[];
  /**
   * 1 (low) .. 5 (high); higher is generated earlier.
   */
  priority: number;
  duplicate: CopySpec1;
}
/**
 * Lets the super reuse a tile instead of generating a new one (cheap filler: open sea, plain
 * desert...). The source must be a non-copy tile in this plan or an accepted tile in the world.
 *
 * - shallow: a linked instance. The copy shares the prototype's art and data, and stays in sync if
 *   the prototype changes later.
 * - deep: an independent snapshot. The copy gets its own record at copy time and never changes
 *   when the prototype does. `copy_of` is kept only as provenance.
 */
export interface CopySpec1 {
  /**
   * 'none' = generate this tile normally.
   */
  mode: "none" | "shallow" | "deep";
  /**
   * Prototype tile q (ignored when mode is 'none').
   */
  source_q: number;
  /**
   * Prototype tile r (ignored when mode is 'none').
   */
  source_r: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "TileDetail".
 */
export interface TileDetail {
  tile: Tile;
  attempts: Attempt[];
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Attempt".
 */
export interface Attempt {
  run_id: string;
  q: number;
  r: number;
  attempt: number;
  directive: Directive;
  design: TileDesign | null;
  asset_id: string | null;
  validation: {
    [k: string]: unknown;
  };
  verdict: Verdict | null;
  outcome: "pending" | "invalid" | "rejected" | "accepted" | "error";
  error: string | null;
  created_at: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "TileDesign".
 */
export interface TileDesign {
  biome: string;
  summary: string;
  attributes: {
    [k: string]: unknown;
  };
  edges: EdgeSpec[];
  art_prompt: string;
  negative_prompt: string;
  relief: number;
  props: PropSpec[];
}
/**
 * A sprite standing on the tile (tree, castle, campfire...). Rendered as its own layer.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "PropSpec".
 */
export interface PropSpec {
  /**
   * What it is, e.g. 'castle', 'pine tree', 'campfire', 'dark obelisk'.
   */
  kind: string;
  /**
   * -0.6 (west) .. 0.6 (east), tile-local.
   */
  x: number;
  /**
   * -0.6 (north) .. 0.6 (south), tile-local.
   */
  y: number;
  /**
   * 0.6 .. 1.6 relative size.
   */
  scale: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Verdict".
 */
export interface Verdict {
  /**
   * The number drawn on the candidate in the composite image.
   */
  label: number;
  accept: boolean;
  scores: Scores;
  /**
   * If rejected: concrete, actionable fix for the tile agent. Else ''.
   */
  feedback: string;
  /**
   * If the landmark sprite itself needs work: an instruction for the sprite artist. Else ''.
   */
  sprite_feedback: string;
  /**
   * If a terrain's shared ground pattern looks wrong: '<material name>: instruction' for the material artist (repaints every tile using it). Else ''.
   */
  material_feedback: string;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Scores".
 */
export interface Scores {
  /**
   * 1-5 consistency with the style guide and anchor tile
   */
  style: number;
  /**
   * 1-5 visual quality / readability
   */
  fidelity: number;
  /**
   * 1-5 how well edges continue into accepted neighbors
   */
  edge_continuity: number;
  /**
   * 1-5 how well it matches its directive
   */
  directive_fit: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  id: number;
  ts: number;
  world_id: string;
  run_id: string | null;
  type: string;
  span_id: string | null;
  parent_span_id: string | null;
  q: number | null;
  r: number | null;
  data: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "StartRun".
 */
export interface StartRun {
  q: number;
  r: number;
  prompt: string;
  options: RunOptions | null;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "EnterResult".
 */
export interface EnterResult {
  world: World;
  run: Run | null;
}
/**
 * A tile seen up close: a layered, animated pixel-art picture of the spot.
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Scene".
 */
export interface Scene {
  world_id: string;
  q: number;
  r: number;
  title: string;
  caption: string;
  layers: SceneLayer[];
  fx: string[];
  created_at: number;
  version: number;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "SceneLayer".
 */
export interface SceneLayer {
  role: "backdrop" | "foreground";
  asset_id: string;
  px_w: number;
  px_h: number;
}
/**
 * Ground just outside a region, continuing its rim terrain so the region blends into its
 * surroundings (rendered by the engine alone, never planned or reviewed).
 *
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "SkirtTile".
 */
export interface SkirtTile {
  q: number;
  r: number;
  ring: number;
  biome: string;
  asset_id: string;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "CreateWorld".
 */
export interface CreateWorld {
  name: string | null;
  radius: number | null;
}
